name: XNU ${MACOS_VERSION}

# on:
  # push:
  #   branches: [ main ]
  #   paths-ignore: [ "*.md" ]
    # tags:
    #   - 'macos/${MACOS_VERSION}*' ???
  # pull_request:
  #   branches: [ main ]
      
jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/template-xnu-build.yml
    with:
      macos-version: '${MACOS_VERSION}'
      xcode-version: '${XCODE_VERSION}'
      machine-config: '${MACHINE_CONFIG}'