name: XNU 13.3

on:
  workflow_dispatch:
# on:
  # push:
  #   branches: [ main ]
  #   paths-ignore: [ "*.md" ]
    # tags:
    #   - 'macos/13.3*' ???
  # pull_request:
  #   branches: [ main ]
      
jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/template-xnu-build.yml
    with:
      macos-version: '13.3'
      xcode-version: '15.2'
      machine-config: 'VMAPPLE'